# Generated by Django 5.0 on 2024-01-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_view_user_id_remove_favorite_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='serie_id',
            new_name='serie',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='serie_id',
            new_name='serie',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='view',
            old_name='serie_id',
            new_name='serie',
        ),
    ]
