# Generated by Django 5.0 on 2024-01-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_view_userviewedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userviewedcontent',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
