# Generated by Django 5.0 on 2024-01-10 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userviewedcontent_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userviewedcontent',
            name='viewed',
        ),
    ]
