# Generated by Django 5.0 on 2024-01-10 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_movie_image'),
        ('user', '0007_remove_userviewedcontent_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userviewedcontent',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.movie'),
        ),
        migrations.AlterField(
            model_name='userviewedcontent',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.serie'),
        ),
    ]
