# Generated by Django 5.0 on 2023-12-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_episode_serie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='serie_id',
        ),
    ]
