# Generated by Django 5.0 on 2023-12-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_episode_serie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
