# Generated by Django 5.0 on 2023-12-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_season_season_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(upload_to='episodes'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='season',
            name='image',
            field=models.ImageField(upload_to='seasons'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='image',
            field=models.ImageField(upload_to='series'),
        ),
    ]
