# Generated by Django 5.0 on 2023-12-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_episode_image_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='director',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
