# Generated by Django 5.0 on 2024-01-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_movie_director_serie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
