# Generated by Django 5.0 on 2024-01-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_movie_image_alter_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
