# Generated by Django 5.0 on 2024-01-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_remove_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
