# Generated by Django 5.0 on 2024-01-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
    ]
